// if you add more users please make sure to up the amount of tracks in generateUserTrackDataSeed function in db/dbHelpers.js file the to reflect this

exports.seed = function (knex) {
  return knex('users')
    .del()
    .then(function () {
      return knex('users').insert([
        {
          id: 1,
          auth0_id: 'auth0|62799026a17ac70069715350',
          name: 'kelmarna',
          email: 'examplaaaaae@example.com',
          description: 'the awesome developer',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'kelmarna',
          status: '',
        },
        {
          id: 2,
          auth0_id: 'auth0|6273103f0b600f00693e3b41',
          name: 'kevin',
          email: 'example@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '500',
          display_name: 'Kevin',
          status: '',
        },
        {
          id: 3,
          auth0_id: 'auth0|627b013d161c0d006f681c47',
          name: 'ahmad',
          email: 'exameerereple@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'Ahmad',
          status: '',
        },
        {
          id: 4,
          auth0_id: 'auth0|627b0bf49ae53600692f8b73',
          name: 'jesse',
          email: 'examplewow@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'jesse',
          status: '',
        },
        {
          id: 5,
          auth0_id: 'auth0|627afc53161c0d006f681c03',
          name: 'tai',
          email: 'example9999@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'tai',
          status: '',
        },
        {
          id: 6,
          auth0_id: 'auth0|627af30200b7d5006998b53d',
          name: 'tiaan',
          email: 'exam34343433ple@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'tiaan',
          status: '',
        },
        {
          id: 7,
          auth0_id: 'auth0|627a0c27f829690067da5b9c',
          name: 'steve',
          email: 'examp232le@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'Steve Jobs',
          status: '',
        },
        {
          id: 8,
          auth0_id: 'auth0|627aea288e78d30068c71c1a',
          name: 'warney',
          email: 'exampleoooo@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'warney',
          status: '',
        },
        {
          id: 9,
          auth0_id: 'auth0|62789b449b80ea00681c7e2a',
          name: 'clementine',
          email: 'exdaaample@example.com',
          description: 'hi',
          rank: 'Bush Lord',
          xp: '1000',
          display_name: 'clementine',
          status: '',
        },
      ])
    })
}
